name: flutter_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Folks
      fonts:
        - asset: assets/fonts/Folks_Regular.ttf
        - asset: assets/fonts/Folks_Bold.ttf
          weight: 700
  assets:
    - assets/icons/CloseDialog.svg
    - assets/illustrations/TimeoutSession.svg
